// <auto-generated />
namespace Practical_12_Test1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Empdbnew12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Empdbnew12));
        
        string IMigrationMetadata.Id
        {
            get { return "202202141047491_Empdbnew12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
