//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practical_14_Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentdata
    {
        public int Id { get; set; }
        public string Sname { get; set; }
        public string Password { get; set; }
    }
}
