//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practical_10.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmpTbl
    {
        public int Id { get; set; }
        [Required (ErrorMessage ="Required Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Required DOB")]
        public string DOB { get; set; }
        public string Address { get; set; }
    }
}
